version: '1.0'
services:
  frontend:
    build: ./FE
    ports:
      - "5173:5173"    
    volumes:
      - ./FE:/app
      - ./logs/frontend:/app/logs
    environment:
      - NODE_ENV=production
    restart: always

  backend:
    build: ./BE
    ports:
      - "3000:3000"    
    volumes:
      - ./BE:/app
      - ./logs/backend:/app/logs
    environment:
      - NODE_ENV=production
    restart: always
